# Generated by Django 2.0 on 2018-07-24 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(verbose_name='Data do Evento')),
                ('event_name', models.CharField(max_length=50, verbose_name='Nome do Evento')),
                ('event_schedule', models.TimeField(verbose_name='Horário do evento')),
                ('value', models.FloatField(verbose_name='Valor do contrato')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tipo Contrato')),
            ],
            options={
                'verbose_name': 'Tipo contrato',
                'verbose_name_plural': 'Tipos de contrato',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contracts.Type'),
        ),
        migrations.AddField(
            model_name='contract',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.Client'),
        ),
    ]
