# Generated by Django 2.0.7 on 2018-08-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_auto_20180809_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='event_hour',
        ),
        migrations.AlterField(
            model_name='contract',
            name='event_date',
            field=models.DateTimeField(verbose_name='Data/Hora do Evento'),
        ),
    ]
