# Generated by Django 2.1 on 2018-08-17 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_auto_20180809_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='note',
            field=models.TextField(default='', verbose_name='Observações'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contracts.Type', verbose_name='Tipo de Evento'),
        ),
    ]
