# Generated by Django 2.0 on 2018-08-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_auto_20180817_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='local',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Local'),
        ),
    ]
