# Generated by Django 2.0 on 2018-07-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('birthday', models.DateField(verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('rg', models.CharField(max_length=18, verbose_name='RG')),
                ('rg_issuer', models.CharField(max_length=50, verbose_name='Orgão Emissor')),
                ('phonenumber', models.CharField(max_length=12, verbose_name='N.Telefone')),
                ('address', models.CharField(max_length=150, verbose_name='Endereço')),
                ('address_bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('postal_code', models.CharField(max_length=9, verbose_name='CEP')),
                ('active', models.BooleanField(default=False, verbose_name='Inativo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Genêro',
                'verbose_name_plural': 'Genêros',
            },
        ),
    ]
