# Generated by Django 2.0.7 on 2018-08-02 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.Gender'),
        ),
        migrations.AddField(
            model_name='client',
            name='phonenumber_2',
            field=models.CharField(default=1, max_length=12, verbose_name='N.Telefone 2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
    ]
