# Generated by Django 2.1 on 2018-08-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20180805_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=150, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address_bairro',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=14, verbose_name='N.Telefone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phonenumber_2',
            field=models.CharField(blank=True, max_length=14, verbose_name='N.Telefone 2'),
        ),
        migrations.AlterField(
            model_name='client',
            name='postal_code',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='client',
            name='rg',
            field=models.CharField(blank=True, max_length=18, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='client',
            name='rg_issuer',
            field=models.CharField(blank=True, max_length=50, verbose_name='Orgão Emissor'),
        ),
    ]
