# Generated by Django 2.0.7 on 2018-08-02 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_auto_20180801_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de avaliação')),
                ('proposal_value', models.FloatField(verbose_name='Valor da Proposta')),
                ('note', models.TextField(verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data Requisição')),
                ('event_date', models.DateField(verbose_name='Data do evento')),
                ('event_name', models.CharField(max_length=180, verbose_name='Nome do Evento')),
                ('note', models.TextField(verbose_name='Observação')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_budget_request', to='clients.Client')),
            ],
            options={
                'verbose_name': 'Solicitação de Orçamento',
                'verbose_name_plural': 'Solicitações de Orçamento',
            },
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.QuoteRequest'),
        ),
    ]
