# Generated by Django 2.0.7 on 2018-08-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20180809_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='event_date',
            field=models.DateTimeField(verbose_name='Data/Hora do evento'),
        ),
    ]
